---
- name: Install nginx Web server
  hosts: all
  become: yes

  tasks:
  - name: Install nginx
    apt: name=nginx state=latest
 
#  - name: Install nginx
#    yum: name=nginx state=latest


  - name: Start nginx and enable
    service: name=nginx state=started enabled=yes